apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.executionService.name }}-sa
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.executionService.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.executionService.name }}-lease-role
  namespace: {{ .Values.global.namespace }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.executionService.name }}-lease-binding
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.executionService.name }}-sa
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.executionService.name }}-lease-role
  apiGroup: rbac.authorization.k8s.io
